[package]
name = "img-resizer"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.21.3"
cfg-if = "1.0.0"
image = "0.24.7"
serde_json = "1.0.105"
worker = "0.0.18"

[lib]
crate-type = ["cdylib", "rlib"]
